### ISSUE TITLE
External reverse proxy for ssl

### ISSUE THREAD

**Issue by JamborJan** [cptn-io/el-cptn#527]
I want to test cptn-io in my current dockerized lab infrastructure where I already have a reverse proxy set up and dealing with ssl certificates. I don't want the frontend (caddy) to do anything about that. How can I simply run the frontend container without any SSL, only having port 80 where I can point my reverse proxy to?

Thank you for creating cptn-io. I am looking forward to get my hands on it.

**Comment by JamborJan** [comment]
Hey @kcthota is there any chance that someone has a look at my question? Once again thanks for creating cptn-io.

**Comment by kcthota** [comment]
We use Caddy as the reverse proxy which provides automatic https. However, you can change it by updating the Caddyfile config at `https://github.com/cptn-io/el-cptn/blob/main/app-ux/Caddyfile`.

I haven't tried it, but set `auto_https off` and use the APP_URL environment variable to start with http://.

Refer the Caddy's documentation here - https://caddyserver.com/docs/caddyfile/options#auto-https

**Comment by JamborJan** [comment]
For anybody stumbling over this, I did the following to use my existing traefik based reverse proxy setup including let's encrypt.

Creates a Caddyfile like this:

```Caddyfile
{
    auto_https off
}

{$APP_URL}:80 {
	encode gzip

	handle /api/* {
		reverse_proxy mgmt-svc:8080
	}

	handle /login {
		reverse_proxy mgmt-svc:8080
	}

	handle /login/* {
        reverse_proxy mgmt-svc:8080
    }

	handle /logout {
		reverse_proxy mgmt-svc:8080
	}

	handle /mgmt/* {
		reverse_proxy mgmt-svc:8080
	}

	handle /oauth2/* {
		reverse_proxy mgmt-svc:8080
	}

	handle /event/* {
		reverse_proxy ingestion-svc:8081
	}

	header / {
        Cache-Control "no-cache, no-store, must-revalidate"
        Pragma "no-cache"
        Expires "0"
    }

	handle {
		root * /usr/share/caddy/ux
		try_files {path} /index.html
		file_server
	}
}
```

Used a Docker Compose file like this:

```yml
# # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Content: cptn-io https://cptn.io/
# Author: Jan Jambor
# Author URI: https://xwr.ch
#
# Required variables:
# - ${POSTGRES_DB_NAME}
# - ${POSTGRES_DB_USER}
# - ${POSTGRES_DB_PASSWORD}
# - ${CPTN_CRYPTO_SECRET}
# - ${JWT_SECRET}
# - ${SETUP_DEFAULT_PASSWORD}
# - ${INSTANCE}
# - ${CT_DATA_BASEPATH}
#
# # # # # # # # # # # # # # # # # # # # # # # # # #

services:
  db:
    # https://hub.docker.com/_/postgres/tags?name=17.
    image: postgres:17.2-alpine3.20
    restart: unless-stopped
    volumes:
      - '${CT_DATA_BASEPATH}/cptn-io_data/postgres:/var/lib/postgresql/data'
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - prd-docker

  # https://hub.docker.com/_/redis/tags?name=alpine
  redis:
    image: redis:7.4.1-alpine3.20
    restart: unless-stopped
    volumes:
      - '${CT_DATA_BASEPATH}/cptn-io_data/redis:/data'
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - prd-docker

  # https://github.com/cptn-io/el-cptn/pkgs/container/app-ux
  app-ux:
    image: ghcr.io/cptn-io/app-ux:latest
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - '${CT_DATA_BASEPATH}/cptn-io_data/caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cptnio-ux.rule=Host(`cptnio.${INSTANCE}.jambor.pro`) && PathPrefix(`/`)"
      - "traefik.http.routers.cptnio-ux.entrypoints=websecure"
      - "traefik.http.routers.cptnio-ux.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.cptnio-ux.service=cptnio-ux"
      - "traefik.http.services.cptnio-ux.loadbalancer.server.port=80"
      - "traefik.http.services.cptnio-ux.loadbalancer.server.scheme=http"
    environment:
      - APP_URL= cptnio.${INSTANCE}.jambor.pro
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - prd-docker

  # https://github.com/cptn-io/el-cptn/pkgs/container/mgmt-svc
  mgmt-svc:
    image: ghcr.io/cptn-io/mgmt-svc:latest
    restart: unless-stopped
    deploy:
      replicas: 1
    expose:
      - 8080
    volumes:
      - '${CT_DATA_BASEPATH}/cptn-io_data/mgmt-svc/logs:/logs'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB_NAME}
      - DB_USER=${POSTGRES_DB_USER}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - CPTN_CRYPTO_SECRET=${CPTN_CRYPTO_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - SETUP_DEFAULT_PASSWORD=${SETUP_DEFAULT_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cptnio-mgmt.rule=Host(`cptnio.${INSTANCE}.yourdomain.com`) && (PathPrefix(`/api`) || PathPrefix(`/login`) || PathPrefix(`/logout`) || PathPrefix(`/mgmt`) || PathPrefix(`/oauth2`))"
      - "traefik.http.routers.cptnio-mgmt.entrypoints=websecure"
      - "traefik.http.routers.cptnio-mgmt.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.cptnio-mgmt.service=cptnio-mgmt"
      - "traefik.http.services.cptnio-mgmt.loadbalancer.server.port=8080"
      - "traefik.http.services.cptnio-mgmt.loadbalancer.server.scheme=http"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep -q 'UP'" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - prd-docker

  # https://github.com/cptn-io/el-cptn/pkgs/container/ingestion-svc
  ingestion-svc:
    image: ghcr.io/cptn-io/ingestion-svc:latest
    restart: unless-stopped
    deploy:
      replicas: 1
    volumes:
      - '${CT_DATA_BASEPATH}/cptn-io_data/ingestion-svc/logs:/logs'
    expose:
      - 8081
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB_NAME}
      - DB_USER=${POSTGRES_DB_USER}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - CPTN_CRYPTO_SECRET=${CPTN_CRYPTO_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cptnio-ingestion.rule=Host(`cptnio.${INSTANCE}.yourdomain.com`) && PathPrefix(`/event`)"
      - "traefik.http.routers.cptnio-ingestion.entrypoints=websecure"
      - "traefik.http.routers.cptnio-ingestion.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.cptnio-ingestion.service=cptnio-ingestion"
      - "traefik.http.services.cptnio-ingestion.loadbalancer.server.port=8081"
      - "traefik.http.services.cptnio-ingestion.loadbalancer.server.scheme=http"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health | grep -q 'UP'" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mgmt-svc:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - prd-docker

  # https://github.com/cptn-io/el-cptn/pkgs/container/processor
  processor:
    image: ghcr.io/cptn-io/processor:latest
    deploy:
      replicas: 1
    volumes:
      - '${CT_DATA_BASEPATH}/cptn-io_data/processor/logs:/app/logs'
    environment:
      - NODE_ENV=production
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=${POSTGRES_DB_NAME}
      - PGUSER=${POSTGRES_DB_USER}
      - PGPASSWORD=${POSTGRES_DB_PASSWORD}
      - PGSSLMODE=disable
      - CPTN_CRYPTO_SECRET=${CPTN_CRYPTO_SECRET}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "ps -ef | grep 'node launcher.js' | grep -v grep > /dev/null || exit 1" ]
      interval: 10s
      timeout: 15s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mgmt-svc:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - prd-docker

networks:
  prd-docker:
    external: true
```
